defmodule AshWorkflow.DocumentationDriftTest do
  @moduledoc """
  Guards the documentation against the DSL moving underneath it.

  `manual true` and the generated `:start` action were both documented long
  after being removed, which meant copy-pasting from the README produced code
  that would not compile. These tests make that a build failure.
  """
  use ExUnit.Case, async: true

  # Docs a user reads and copies from. The generated DSL reference is excluded:
  # it is regenerated by `mix spark.cheat_sheets`, so it cannot drift.
  @doc_files ["README.md", "usage-rules.md" | Path.wildcard("usage-rules/*.md")]

  # Names that used to be part of the public DSL. Add to this list when
  # removing an option, so nothing can quietly document it again. Patterns are
  # matched as regexes so prose like "a manual step" is not a false positive.
  @retired_names [
    {~S"manual\s+true", "a step is manual when it declares transitions"},
    {~S":start\b(?!_)", "workflows are started through your own create action"},
    {~S"\bstart/1", "workflows are started through your own create action"}
  ]

  describe "every DSL option is documented" do
    for {entity_path, option} <- AshWorkflowTest.DslIntrospection.dsl_options() do
      test "#{Enum.join(entity_path, ".")} option `#{option}` appears in the usage rules" do
        option = unquote(option)
        entity_path = unquote(entity_path)

        documented? =
          Enum.any?(["usage-rules.md" | Path.wildcard("usage-rules/*.md")], fn file ->
            String.contains?(File.read!(file), to_string(option))
          end)

        assert documented?, """
        The DSL option `#{option}` on `#{Enum.join(entity_path, ".")}` is not \
        mentioned anywhere in usage-rules.md or usage-rules/.

        The usage rules are what LLM coding agents read to use this library, so \
        an undocumented option is effectively invisible. Document it, or add it \
        to @retired_names if it is being removed.
        """
      end
    end
  end

  describe "retired DSL names are not documented" do
    for file <- @doc_files, {name, reason} <- @retired_names do
      test "#{file} does not use the retired `#{name}`" do
        contents = File.read!(unquote(file))
        {pattern, reason} = {unquote(name), unquote(reason)}

        refute Regex.match?(Regex.compile!(pattern), contents), """
        #{unquote(file)} still uses `#{pattern}`, which is no longer part of \
        the DSL — #{reason}.
        """
      end
    end
  end
end
