defmodule AshWorkflow.DocumentationDriftTest do
  @moduledoc """
  Guards the documentation against the DSL and the implementation moving
  underneath it.

  `manual true` and the generated `:start` action were both documented long
  after being removed, which meant copy-pasting from the README produced code
  that would not compile. Later, `documentation/topics/error-handling.md`
  described a failure path the library had replaced two releases earlier, and
  the timeouts guide recommended a cron expression a verifier rejects. Neither
  was caught, because the guides were not checked at all and the checks that
  existed only looked for option names.

  These tests make all three kinds of drift a build failure: an option nothing
  documents, a name or claim that is no longer true, and a reference to an
  `AshWorkflow` function that does not exist.
  """
  use ExUnit.Case, async: true

  # Docs a user reads and copies from. The generated DSL reference is excluded:
  # it is regenerated by `mix spark.cheat_sheets`, so it cannot drift. The
  # design notes under documentation/design are excluded too — they record why
  # a decision was made at a point in time, so they are allowed to describe
  # alternatives the library does not implement.
  @doc_files [
    "README.md",
    "usage-rules.md"
    | Path.wildcard("usage-rules/*.md") ++
        Path.wildcard("documentation/topics/*.md") ++
        Path.wildcard("documentation/tutorials/*.md")
  ]

  # Names that used to be part of the public DSL. Add to this list when
  # removing an option, so nothing can quietly document it again. Patterns are
  # matched as regexes so prose like "a manual step" is not a false positive.
  # The retired `:start` action is matched only where it would be declared or
  # called, because `:start` is also the suffix of every telemetry span this
  # library emits and `documentation/topics/telemetry.md` names it correctly.
  @retired_names [
    {~S"manual\s+true", "a step is manual when it declares transitions"},
    {~S"(?:action|define|transition)\s+:start\b",
     "workflows are started through your own create action"},
    {~S"\bstart/1", "workflows are started through your own create action"},
    {~S"check_interval:?\s+false",
     "check_interval is a cron string; `self_scheduled?: true` is what opts a timeout out of polling"},
    {~S"(?<!fire_)\bafter:", "a timeout's duration option is `fire_after`, not `after`"}
  ]

  # Claims about behaviour that were documented after the behaviour changed.
  # A pattern here must not appear in any doc file, and the reason names what
  # is true instead. Unlike @retired_names these are statements rather than
  # identifiers, so each one is anchored on wording specific enough that a
  # rewrite of the surrounding prose does not resurrect it by accident.
  @retired_claims [
    {~S"does not automatically perform this transition",
     "AshWorkflow.Transformers.AddActions generates __on_error_<step> and AddScheduler wires it to the trigger, so the transition to the error state does happen automatically"},
    {~S"the record remains in `:process`",
     "a step with on_error moves to the error state on the first failure"},
    {~S"\*\s\*\s\*\s\*\s\*\s\*",
     "Oban cron cannot poll below one minute, and AshWorkflow.Verifiers.ValidateTimeoutPrecision rejects a sub-minute deadline unless the timeout is self_scheduled? or the workflow selects AshWorkflow.Scheduler.Precise"}
  ]

  # Mechanisms a guide has to name to be worth reading. Each is the piece of
  # the implementation the guide's subject is actually built on, so a guide
  # that stops naming it has either gone stale or gone vague.
  @required_mechanisms [
    {"documentation/topics/error-handling.md", ~S"__on_error_",
     "the generated action that performs the on_error transition"},
    {"documentation/topics/error-handling.md", ~S":error_path",
     "the triggered_by value the on_error path writes to the transition log"},
    {"documentation/topics/timeouts-and-deadlines.md", ~S"AshWorkflow\.Scheduler\.Precise",
     "the scheduler that arms a timer per deadline, and the only supported route to sub-minute precision"},
    {"documentation/topics/timeouts-and-deadlines.md", ~S"self_scheduled\?",
     "the option that opts one timeout out of polling"},
    {"documentation/tutorials/getting-started-with-ash-workflow.md",
     ~S"mix igniter\.install ash_workflow",
     "the supported installation path, which configures Oban and the queue for the reader"}
  ]

  describe "every DSL option is documented" do
    for {entity_path, option} <- AshWorkflowTest.DslIntrospection.dsl_options() do
      test "#{Enum.join(entity_path, ".")} option `#{option}` appears in the usage rules" do
        option = unquote(option)
        entity_path = unquote(entity_path)

        documented? =
          Enum.any?(["usage-rules.md" | Path.wildcard("usage-rules/*.md")], fn file ->
            String.contains?(File.read!(file), to_string(option))
          end)

        assert documented?, """
        The DSL option `#{option}` on `#{Enum.join(entity_path, ".")}` is not \
        mentioned anywhere in usage-rules.md or usage-rules/.

        The usage rules are what LLM coding agents read to use this library, so \
        an undocumented option is effectively invisible. Document it, or add it \
        to @retired_names if it is being removed.
        """
      end
    end
  end

  describe "retired DSL names are not documented" do
    for file <- @doc_files, {name, reason} <- @retired_names do
      test "#{file} does not use the retired `#{name}`" do
        contents = File.read!(unquote(file))
        {pattern, reason} = {unquote(name), unquote(reason)}

        refute Regex.match?(Regex.compile!(pattern), contents), """
        #{unquote(file)} still uses `#{pattern}`, which is no longer part of \
        the DSL — #{reason}.
        """
      end
    end
  end

  describe "retired claims about behaviour are not documented" do
    for file <- @doc_files, {claim, reason} <- @retired_claims do
      test "#{file} does not claim `#{claim}`" do
        contents = File.read!(unquote(file))
        {pattern, reason} = {unquote(claim), unquote(reason)}

        refute Regex.match?(Regex.compile!(pattern), contents), """
        #{unquote(file)} still makes a claim the implementation contradicts, \
        matching `#{pattern}`.

        What is true instead: #{reason}.
        """
      end
    end
  end

  describe "each guide names the mechanism it documents" do
    for {file, pattern, what} <- @required_mechanisms do
      test "#{file} names #{what}" do
        contents = File.read!(unquote(file))
        {pattern, what} = {unquote(pattern), unquote(what)}

        assert Regex.match?(Regex.compile!(pattern), contents), """
        #{unquote(file)} no longer names #{what}, expected to match \
        `#{pattern}`.

        A guide that stops naming the mechanism it documents has either gone \
        stale or gone vague. If the mechanism was replaced, update this list \
        to name the replacement.
        """
      end
    end
  end

  # `step :approved, terminal: true` and `step :review do ... end` both
  # compile; the two together do not, because the block becomes a third
  # argument. Matched on the entities that take a block.
  @options_and_block ~r/^\s*(?:step|transition|timeout|transition_log)\s+:[a-z_]+,\s*[a-z_]+[?]?:.*\bdo\s*$/m

  describe "documented DSL calls compile" do
    for file <- @doc_files do
      test "#{file} passes no options and a block to the same entity" do
        file = unquote(file)

        offenders =
          file
          |> File.read!()
          |> then(&Regex.scan(@options_and_block, &1))
          |> Enum.map(&List.first/1)
          |> Enum.uniq()

        assert offenders == [], """
        #{file} passes both options and a `do` block to a DSL entity:

        #{Enum.map_join(offenders, "\n", &"  #{&1}")}

        Elixir parses that as a three-argument call, and Spark defines each         entity macro with two, so the example does not compile. Set the option         inside the block instead — `step :intake do initial true ... end`.
        """
      end
    end
  end

  describe "every AshWorkflow function the docs reference exists" do
    for file <- @doc_files ++ Path.wildcard("lib/**/*.ex") do
      test "#{file} references only functions that are defined" do
        file = unquote(file)

        missing =
          file
          |> File.read!()
          |> referenced_functions()
          |> Enum.reject(&defined?/1)

        assert missing == [], """
        #{file} references #{length(missing)} AshWorkflow function(s) that are \
        not defined:

        #{Enum.map_join(missing, "\n", fn {m, f, a} -> "  #{inspect(m)}.#{f}/#{a}" end)}

        A reader who follows the reference gets nothing, and `mix docs` emits \
        an unresolved-reference warning for each one. Name the function that \
        exists, or delete the reference.
        """
      end
    end
  end

  # Matches an `AshWorkflow`-scoped `Module.function/arity` inside backticks.
  # Scoped to this library because a reference into ash, ash_oban or Oban
  # depends on a version this test does not pin.
  @reference ~r/`(AshWorkflow(?:\.[A-Z][A-Za-z0-9_]*)*)\.([a-z_][A-Za-z0-9_]*[?!]?)\/(\d+)`/

  defp referenced_functions(contents) do
    @reference
    |> Regex.scan(contents)
    |> Enum.map(fn [_full, module, function, arity] ->
      {Module.concat([module]), String.to_atom(function), String.to_integer(arity)}
    end)
    |> Enum.uniq()
  end

  defp defined?({module, function, arity}) do
    Code.ensure_loaded?(module) and
      (function_exported?(module, function, arity) or
         macro_exported?(module, function, arity))
  end
end
