defmodule AshWorkflowTest.Postgres.AuthorizedOnSuccessObanTest do
  @moduledoc """
  Exercises conditional `on_success` against a real database and a real Oban,
  on a resource with an authorizer and a step-level policy elsewhere in the
  workflow — the gap `on_success_oban_test.exs` leaves, since
  `ScreeningWorkflow` there has no authorizer at all.

  `demos/README.md` records that `on_error` was once forbidden by the
  generated policies on any authorizer-bearing resource, because its
  `__on_error_*` action lived outside the generated bypass/default-allow
  scopes, so a failing step silently stayed put. `on_success` doesn't
  generate a separate action per target — every route is evaluated inside the
  step's own action — so there's no analogous per-target action to leave
  uncovered. These tests prove that holds: every conditional `on_success`
  target, including the "rejection" one, is actually reachable through a
  real, actor-less Oban run.
  """
  use AshWorkflowTest.DataCase

  alias AshWorkflowTest.Postgres.AuthorizedScreeningWorkflow

  defp submit(attrs \\ %{}) do
    AuthorizedScreeningWorkflow.submit!(Map.merge(%{candidate_name: "Some Candidate"}, attrs))
  end

  defp run_trigger! do
    AshOban.schedule_and_run_triggers(AuthorizedScreeningWorkflow)
    assert %{failure: 0, discard: 0} = Oban.drain_queue(queue: :workflow, with_recursion: true)
  end

  test "the happy target is reachable with an authorizer configured" do
    workflow = submit(%{candidate_name: "Strong Candidate"})
    assert workflow.state == :screening

    run_trigger!()

    reloaded = Ash.get!(AuthorizedScreeningWorkflow, workflow.id, authorize?: false)
    assert reloaded.state == :interview
  end

  test "the rejection target is equally reachable — the historical bug pattern would have silently left this stuck" do
    workflow = submit(%{candidate_name: "Weak Candidate"})
    assert workflow.state == :screening

    run_trigger!()

    reloaded = Ash.get!(AuthorizedScreeningWorkflow, workflow.id, authorize?: false)
    assert reloaded.state == :rejected_by_hr
  end

  test "on_error is also reachable on this authorized resource, same as the unconditional case" do
    workflow = submit(%{candidate_name: "Strong Candidate", should_fail: true})

    run_trigger!()

    reloaded = Ash.get!(AuthorizedScreeningWorkflow, workflow.id, authorize?: false)
    assert reloaded.state == :screening_failed
  end

  test "the interview step's own policy still gates its transition, unaffected by the automatic step's bypass" do
    workflow = submit(%{candidate_name: "Strong Candidate"})
    run_trigger!()
    interview = Ash.get!(AuthorizedScreeningWorkflow, workflow.id, authorize?: false)
    assert interview.state == :interview

    assert {:error, _forbidden} =
             Ash.update(interview, action: :schedule, actor: %{role: :candidate})

    assert {:ok, scheduled} =
             Ash.update(interview, action: :schedule, actor: %{role: :interviewer})

    assert scheduled.state == :scheduled
  end
end
