spark_locals_without_parens = [
  accept: 1,
  action: 1,
  backoff: 1,
  belongs_to_actor: 2,
  belongs_to_actor: 3,
  check_interval: 1,
  every: 1,
  every: 2,
  every: 3,
  field: 1,
  fire_after: 1,
  fire_at: 1,
  generate_indexes?: 1,
  initial: 1,
  interval: 1,
  max_attempts: 1,
  on_error: 1,
  on_success: 1,
  on_success: 2,
  policy: 1,
  queue: 1,
  retry: 0,
  retry: 1,
  route: 1,
  route: 2,
  same_actor?: 1,
  scheduler: 1,
  self_scheduled?: 1,
  state_attribute: 1,
  step: 1,
  step: 2,
  terminal: 1,
  timeout: 1,
  timeout: 2,
  to: 1,
  transition: 1,
  transition: 2,
  transition_log: 1,
  transition_log: 2,
  transition_to: 1,
  undo: 0,
  undo: 1,
  undoable?: 1,
  until: 1,
  when: 1,
  within: 1
]

# Used by "mix format"
[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  plugins: [Spark.Formatter],
  import_deps: [:ash],
  locals_without_parens: spark_locals_without_parens,
  export: [
    locals_without_parens: spark_locals_without_parens
  ]
]
