defmodule DocumentApproval.Repo.Migrations.AddEveryLastFiredColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:documents) do
      add(:in_review_nudge_last_fired_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:documents) do
      remove(:in_review_nudge_last_fired_at)
    end
  end
end
