defmodule DocumentApproval.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:documents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:title, :text, null: false)
      add(:body, :text, null: false)
      add(:author_email, :text, null: false)
      add(:first_approver_id, :uuid)
      add(:second_approver_id, :uuid)
      add(:rejection_reason, :text)
      add(:nudges_sent, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "validating")
    end
  end

  def down do
    drop(table(:documents))
  end
end
