defmodule DocumentApproval.Repo.Migrations.AddEveryLastFiredColumns1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:documents, [:state, :in_review_nudge_last_fired_at],
             name: "ash_workflow_documents_state_in_review_nudge_last_fired_at_index",
             concurrently: true
           )

    create index(:documents, [:state, :state_entered_at],
             name: "ash_workflow_documents_state_state_entered_at_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists(
      index(:documents, [:state, :state_entered_at],
        name: "ash_workflow_documents_state_state_entered_at_index"
      )
    )

    drop_if_exists(
      index(:documents, [:state, :in_review_nudge_last_fired_at],
        name: "ash_workflow_documents_state_in_review_nudge_last_fired_at_index"
      )
    )
  end
end
