defmodule SubscriptionDunning.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subscriptions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:customer_email, :text, null: false)
      add(:plan, :text, null: false)
      add(:monthly_cents, :bigint, null: false)
      add(:grace_period_ends_at, :utc_datetime_usec)
      add(:dunning_emails_sent, :bigint, null: false, default: 0)
      add(:final_notice_sent?, :boolean, null: false, default: false)
      add(:cancellation_reason, :text)

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "active")
    end
  end

  def down do
    drop(table(:subscriptions))
  end
end
