defmodule SubscriptionDunning.Repo.Migrations.AddActionTimeoutFiredColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscriptions) do
      add(:suspended_final_notice_fired_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:subscriptions) do
      remove(:suspended_final_notice_fired_at)
    end
  end
end
