defmodule SubscriptionDunning.Repo.Migrations.AddEveryLastFiredColumns1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:subscriptions, [:state, :grace_period_dunning_email_last_fired_at],
             name:
               "ash_workflow_subscriptions_state_grace_period_dunning_email_last_fired_at_index",
             concurrently: true
           )

    create index(:subscriptions, [:state, :grace_period_ends_at],
             name: "ash_workflow_subscriptions_state_grace_period_ends_at_index",
             concurrently: true
           )

    create index(:subscriptions, [:state, :state_entered_at],
             name: "ash_workflow_subscriptions_state_state_entered_at_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists(
      index(:subscriptions, [:state, :state_entered_at],
        name: "ash_workflow_subscriptions_state_state_entered_at_index"
      )
    )

    drop_if_exists(
      index(:subscriptions, [:state, :grace_period_ends_at],
        name: "ash_workflow_subscriptions_state_grace_period_ends_at_index"
      )
    )

    drop_if_exists(
      index(:subscriptions, [:state, :grace_period_dunning_email_last_fired_at],
        name: "ash_workflow_subscriptions_state_grace_period_dunning_email_last_fired_at_index"
      )
    )
  end
end
