defmodule AshWorkflow.Transformers.AddStateMachineTest do
  use ExUnit.Case

  alias AshWorkflowTest.Workflow

  test "generates correct states from steps" do
    all_states = AshStateMachine.Info.state_machine_all_states(Workflow)

    assert :process_application in all_states
    assert :review in all_states
    assert :approved in all_states
    assert :rejected in all_states
    assert :escalated in all_states
  end

  test "first non-terminal step is the initial state" do
    assert {:ok, :process_application} =
             AshStateMachine.Info.state_machine_default_initial_state(Workflow)

    assert {:ok, [:process_application]} =
             AshStateMachine.Info.state_machine_initial_states(Workflow)
  end

  test "generates transitions for automatic steps" do
    transitions = AshStateMachine.Info.state_machine_transitions(Workflow)

    assert Enum.any?(transitions, fn t ->
             t.action == :process_application and
               :process_application in t.from and
               :review in t.to
           end)
  end

  test "generates transitions for manual step transitions" do
    transitions = AshStateMachine.Info.state_machine_transitions(Workflow)

    assert Enum.any?(transitions, fn t ->
             t.action == :approve and :review in t.from and :approved in t.to
           end)

    assert Enum.any?(transitions, fn t ->
             t.action == :reject and :review in t.from and :rejected in t.to
           end)
  end

  test "generates transitions for timeout with transition_to" do
    transitions = AshStateMachine.Info.state_machine_transitions(Workflow)

    assert Enum.any?(transitions, fn t ->
             t.action == :__timeout_escalation and :review in t.from and :escalated in t.to
           end)
  end

  test "adds state_entered_at attribute" do
    attr = Ash.Resource.Info.attribute(Workflow, :state_entered_at)
    assert attr != nil
    assert attr.type == Ash.Type.UtcDatetimeUsec
    assert attr.allow_nil? == true
  end

  test "state attribute is generated by ash_state_machine" do
    attr = Ash.Resource.Info.attribute(Workflow, :state)
    assert attr != nil
    assert attr.type == Ash.Type.Atom
    assert attr.allow_nil? == false
  end
end
