defmodule SupportTicketSla.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:subject, :text, null: false)
      add(:requester_email, :text, null: false)
      add(:priority, :text, null: false, default: "normal")
      add(:resolution, :text)
      add(:sla_warnings_sent, :bigint, null: false, default: 0)
      add(:stale_flags, :bigint, null: false, default: 0)

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "triaging")
    end
  end

  def down do
    drop(table(:tickets))
  end
end
