defmodule SupportTicketSla.Repo.Migrations.AddActionTimeoutFiredColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add(:urgent_queue_warn_fired_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:tickets) do
      remove(:urgent_queue_warn_fired_at)
    end
  end
end
