defmodule AshWorkflowTest.Domain do
  @moduledoc false
  use Ash.Domain

  resources do
    resource AshWorkflowTest.Workflow
    resource AshWorkflowTest.LinearWorkflow
    resource AshWorkflowTest.ApprovalWorkflow
    resource AshWorkflowTest.TimeoutWorkflow
    resource AshWorkflowTest.PolicyWorkflow
    resource AshWorkflowTest.FullPipeline
    resource AshWorkflowTest.LoopbackWorkflow
    resource AshWorkflowTest.CustomActionWorkflow
    resource AshWorkflowTest.ConditionalWorkflow
    resource AshWorkflowTest.SharedTransitionWorkflow
    resource AshWorkflowTest.SharedConditionalWorkflow
    resource AshWorkflowTest.AcceptWorkflow
    resource AshWorkflowTest.AcceptedRouteWorkflow
    resource AshWorkflowTest.InitialFlagWorkflow
    resource AshWorkflowTest.DerivedTerminalWorkflow
    resource AshWorkflowTest.RepeatingTimeoutWorkflow
    resource AshWorkflowTest.CustomQueueWorkflow
    resource AshWorkflowTest.FieldTimeoutWorkflow
    resource AshWorkflowTest.ExprCalcTimeoutWorkflow
    resource AshWorkflowTest.CustomSchedulerWorkflow
    resource AshWorkflowTest.OneMinuteWorkflow
    resource AshWorkflowTest.PreciseTimeoutWorkflow
    resource AshWorkflowTest.PreciseDeadlineWorkflow
    resource AshWorkflowTest.RaisingStepWorkflow
    resource AshWorkflowTest.SixtySecondsWorkflow
    resource AshWorkflowTest.WaitStateWorkflow
    resource AshWorkflowTest.NonPrimaryReadWorkflow
    resource AshWorkflowTest.FailingRouteWorkflow
    resource AshWorkflowTest.ErrorPathWorkflow
    resource AshWorkflowTest.CheckIntervalWorkflow
    resource AshWorkflowTest.AuthorizedErrorPathWorkflow
    resource AshWorkflowTest.SharedTimeoutNameWorkflow
    resource AshWorkflowTest.LoggedWorkflow
    resource AshWorkflowTest.LoggedTransition
    resource AshWorkflowTest.Reviewer
    resource AshWorkflowTest.UndoWorkflow
    resource AshWorkflowTest.UndoLog
    resource AshWorkflowTest.SameActorUndoWorkflow
    resource AshWorkflowTest.SameActorUndoLog
    resource AshWorkflowTest.BackfillWorkflow
    resource AshWorkflowTest.BackfillTransition
    resource AshWorkflowTest.OnSuccessWorkflow
    resource AshWorkflowTest.OnSuccessShorthandWorkflow
    resource AshWorkflowTest.OnSuccessFallbackWorkflow
    resource AshWorkflowTest.OnSuccessNilConditionWorkflow
    resource AshWorkflowTest.OnSuccessThreeWayWorkflow
    resource AshWorkflowTest.OnSuccessSelfLoopWorkflow
    resource AshWorkflowTest.OnSuccessBackwardLoopWorkflow
    resource AshWorkflowTest.OnSuccessCalculationWorkflow
    resource AshWorkflowTest.StatusWorkflow
    resource AshWorkflowTest.StatusLog
  end
end
