defmodule AshWorkflowDemo.Repo.Migrations.AddCandidateTransition do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:candidates_transitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :from_state, :text
      add :to_state, :text, null: false
      add :transition_name, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :triggered_by, :text, null: false

      add :candidate_id,
          references(:candidates,
            column: :id,
            name: "candidates_transitions_candidate_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :undoes_id,
          references(:candidates_transitions,
            column: :id,
            name: "candidates_transitions_undoes_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:candidates_transitions, [:candidate_id, :occurred_at])
  end

  def down do
    drop_if_exists index(:candidates_transitions, [:candidate_id, :occurred_at])

    drop constraint(:candidates_transitions, "candidates_transitions_undoes_id_fkey")

    drop constraint(:candidates_transitions, "candidates_transitions_candidate_id_fkey")

    drop table(:candidates_transitions)
  end
end
