defmodule AshWorkflowDemo.Repo.Migrations.AddDbsCheckAndReviewerPipeline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:candidates) do
      add :hr_delay_seconds, :bigint
      add :lead_delay_seconds, :bigint
      add :hr_respond_after, :utc_datetime_usec
      add :lead_respond_after, :utc_datetime_usec
      add :lead_score, :bigint
      add :lead_note, :text
      add :dbs_reference, :text
      add :dbs_offence, :text
      modify :state, :text, default: "hr_screen"
      remove :verify_after
    end

    create index(:candidates, [:dbs_reference], unique: true, where: "dbs_reference is not null")
  end

  def down do
    drop_if_exists index(:candidates, [:dbs_reference])

    alter table(:candidates) do
      add :verify_after, :utc_datetime_usec
      modify :state, :text, default: "submitted"
      remove :dbs_offence
      remove :dbs_reference
      remove :lead_note
      remove :lead_score
      remove :lead_respond_after
      remove :hr_respond_after
      remove :lead_delay_seconds
      remove :hr_delay_seconds
    end
  end
end
