defmodule AshWorkflowDemo.Repo.Migrations.AddSubmittedWaitState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:candidates) do
      modify :state, :text, default: "submitted"
      add :verify_after, :utc_datetime_usec
    end
  end

  def down do
    alter table(:candidates) do
      remove :verify_after
      modify :state, :text, default: "verifying"
    end
  end
end
