defmodule AshWorkflowDemo.Repo.Migrations.AddDbsCheckAndReviewerPipeline1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:candidates, [:state, :lead_respond_after],
             name: "ash_workflow_candidates_state_lead_respond_after_index",
             concurrently: true
           )

    create index(:candidates, [:state, :hr_respond_after],
             name: "ash_workflow_candidates_state_hr_respond_after_index",
             concurrently: true
           )

    create index(:candidates, [:state, :state_entered_at],
             name: "ash_workflow_candidates_state_state_entered_at_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists index(:candidates, [:state, :state_entered_at],
                     name: "ash_workflow_candidates_state_state_entered_at_index"
                   )

    drop_if_exists index(:candidates, [:state, :hr_respond_after],
                     name: "ash_workflow_candidates_state_hr_respond_after_index"
                   )

    drop_if_exists index(:candidates, [:state, :lead_respond_after],
                     name: "ash_workflow_candidates_state_lead_respond_after_index"
                   )
  end
end
