defmodule AshWorkflowDemo.Repo.Migrations.AddBureauClockAndRetry1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:candidates, [:state, :dbs_respond_after],
             name: "ash_workflow_candidates_state_dbs_respond_after_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists index(:candidates, [:state, :dbs_respond_after],
                     name: "ash_workflow_candidates_state_dbs_respond_after_index"
                   )
  end
end
