defmodule AshWorkflowDemo.Repo.Migrations.AddBureauClockAndRetry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:candidates) do
      add :dbs_respond_after, :utc_datetime_usec
      add :bureau_flaky?, :boolean, default: false
      add :bureau_attempts, :bigint, default: 0
    end
  end

  def down do
    alter table(:candidates) do
      remove :bureau_attempts
      remove :bureau_flaky?
      remove :dbs_respond_after
    end
  end
end
