defmodule WorkflowTimeline.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:incident_transitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :from_state, :text
      add :to_state, :text, null: false
      add :transition_name, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :triggered_by, :text, null: false
      add :incident_id, :uuid, null: false
      add :responder_id, :uuid
    end

    create index(:incident_transitions, [:incident_id, :occurred_at])

    create table(:incidents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:incident_transitions) do
      modify :incident_id,
             references(:incidents,
               column: :id,
               name: "incident_transitions_incident_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:incidents) do
      add :title, :text, null: false
      add :description, :text, null: false
      add :severity, :text
      add :status_updates_sent, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "triaging"
    end

    create table(:responders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:incident_transitions) do
      modify :responder_id,
             references(:responders,
               column: :id,
               name: "incident_transitions_responder_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:responders) do
      add :name, :text, null: false
      add :team, :text, null: false
    end
  end

  def down do
    alter table(:responders) do
      remove :team
      remove :name
    end

    drop constraint(:incident_transitions, "incident_transitions_responder_id_fkey")

    drop constraint(:incident_transitions, "incident_transitions_incident_id_fkey")

    alter table(:incident_transitions) do
      modify :responder_id, :uuid
    end

    drop table(:responders)

    alter table(:incidents) do
      remove :state
      remove :state_entered_at
      remove :updated_at
      remove :inserted_at
      remove :status_updates_sent
      remove :severity
      remove :description
      remove :title
    end

    alter table(:incident_transitions) do
      modify :incident_id, :uuid
    end

    drop table(:incidents)

    drop_if_exists index(:incident_transitions, [:incident_id, :occurred_at])

    drop table(:incident_transitions)
  end
end
