defmodule WorkflowTimeline.Repo.Migrations.AddUndoableIncidents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:undoable_incident_transitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :from_state, :text
      add :to_state, :text, null: false
      add :transition_name, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :triggered_by, :text, null: false
      add :undoable_incident_id, :uuid, null: false

      add :undoes_id,
          references(:undoable_incident_transitions,
            column: :id,
            name: "undoable_incident_transitions_undoes_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :responder_id,
          references(:responders,
            column: :id,
            name: "undoable_incident_transitions_responder_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:undoable_incident_transitions, [:undoable_incident_id, :occurred_at])

    create table(:undoable_incidents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:undoable_incident_transitions) do
      modify :undoable_incident_id,
             references(:undoable_incidents,
               column: :id,
               name: "undoable_incident_transitions_undoable_incident_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:undoable_incidents) do
      add :title, :text, null: false
      add :description, :text, null: false
      add :severity, :text
      add :status_updates_sent, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "triaging"
    end
  end

  def down do
    alter table(:undoable_incidents) do
      remove :state
      remove :state_entered_at
      remove :updated_at
      remove :inserted_at
      remove :status_updates_sent
      remove :severity
      remove :description
      remove :title
    end

    drop constraint(
           :undoable_incident_transitions,
           "undoable_incident_transitions_responder_id_fkey"
         )

    drop constraint(
           :undoable_incident_transitions,
           "undoable_incident_transitions_undoes_id_fkey"
         )

    drop constraint(
           :undoable_incident_transitions,
           "undoable_incident_transitions_undoable_incident_id_fkey"
         )

    alter table(:undoable_incident_transitions) do
      modify :undoable_incident_id, :uuid
    end

    drop table(:undoable_incidents)

    drop_if_exists index(:undoable_incident_transitions, [:undoable_incident_id, :occurred_at])

    drop table(:undoable_incident_transitions)
  end
end
