defmodule WorkflowTimeline.Repo.Migrations.AddEveryLastFiredColumns1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:incidents, [:state, :investigating_status_reminder_last_fired_at],
             name:
               "ash_workflow_incidents_state_investigating_status_reminder_last_fired_at_index",
             concurrently: true
           )

    create index(:incidents, [:state, :state_entered_at],
             name: "ash_workflow_incidents_state_state_entered_at_index",
             concurrently: true
           )

    create index(:undoable_incidents, [:state, :investigating_status_reminder_last_fired_at],
             name:
               "ash_workflow_undoable_incidents_state_investigating_status_reminder_last_fired_at_index",
             concurrently: true
           )

    create index(:undoable_incidents, [:state, :state_entered_at],
             name: "ash_workflow_undoable_incidents_state_state_entered_at_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists index(:undoable_incidents, [:state, :state_entered_at],
                     name: "ash_workflow_undoable_incidents_state_state_entered_at_index"
                   )

    drop_if_exists index(
                     :undoable_incidents,
                     [:state, :investigating_status_reminder_last_fired_at],
                     name:
                       "ash_workflow_undoable_incidents_state_investigating_status_reminder_last_fired_at_index"
                   )

    drop_if_exists index(:incidents, [:state, :state_entered_at],
                     name: "ash_workflow_incidents_state_state_entered_at_index"
                   )

    drop_if_exists index(:incidents, [:state, :investigating_status_reminder_last_fired_at],
                     name:
                       "ash_workflow_incidents_state_investigating_status_reminder_last_fired_at_index"
                   )
  end
end
