defmodule WorkflowTimeline.Repo.Migrations.AddEveryLastFiredColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:incidents) do
      add :investigating_status_reminder_last_fired_at, :utc_datetime_usec
    end

    alter table(:undoable_incidents) do
      add :investigating_status_reminder_last_fired_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:undoable_incidents) do
      remove :investigating_status_reminder_last_fired_at
    end

    alter table(:incidents) do
      remove :investigating_status_reminder_last_fired_at
    end
  end
end
