defmodule AshWorkflowTest.AuthorizedErrorPathWorkflow do
  @moduledoc """
  An automatic step with an `on_error` target on a resource that has an
  authorizer, so the generated `__on_error_*` action is covered by policies.

  AshOban invokes that action, and it has no actor, so it has to be covered by
  the generated bypass — otherwise a failing step is silently forbidden from
  routing to its error state.
  """

  use Ash.Resource,
    domain: AshWorkflowTest.Domain,
    data_layer: Ash.DataLayer.Ets,
    authorizers: [Ash.Policy.Authorizer],
    extensions: [AshWorkflow, AshOban]

  workflow do
    step :processing do
      action :process
      on_success :done
      on_error :failed
    end

    step :done, terminal: true
    step :failed, terminal: true
  end

  code_interface do
    define :create
  end

  actions do
    create :create do
      accept [:title]
    end

    update :process do
      accept []
    end
  end

  attributes do
    uuid_v7_primary_key :id
    attribute :title, :string, allow_nil?: false
  end
end
