defmodule OrderFulfilment.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:reference, :text, null: false)
      add(:total_cents, :bigint, null: false)
      add(:card_valid?, :boolean, null: false, default: true)
      add(:stock_available?, :boolean, null: false, default: true)
      add(:address_valid?, :boolean, null: false, default: true)
      add(:charge_reference, :text)
      add(:tracking_number, :text)
      add(:payment_attempts, :bigint, null: false, default: 0)
      add(:supplier_chases, :bigint, null: false, default: 0)
      add(:cancellation_reason, :text)

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "charging_card")
    end
  end

  def down do
    drop(table(:orders))
  end
end
