defmodule OrderFulfilment.Repo.Migrations.AddEveryLastFiredColumns1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:orders, [:state, :backordered_chase_supplier_last_fired_at],
             name: "ash_workflow_orders_state_backordered_chase_supplier_last_fired_at_index",
             concurrently: true
           )

    create index(:orders, [:state, :state_entered_at],
             name: "ash_workflow_orders_state_state_entered_at_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists(
      index(:orders, [:state, :state_entered_at],
        name: "ash_workflow_orders_state_state_entered_at_index"
      )
    )

    drop_if_exists(
      index(:orders, [:state, :backordered_chase_supplier_last_fired_at],
        name: "ash_workflow_orders_state_backordered_chase_supplier_last_fired_at_index"
      )
    )
  end
end
