defmodule AshWorkflowDemo.DemoSchedulerTest do
  use ExUnit.Case, async: true

  alias AshWorkflowDemo.ATS.Candidate
  alias AshWorkflowDemo.DemoScheduler

  test "every trigger the scheduler drives is generated by the workflow" do
    generated = Enum.map(AshOban.Info.oban_triggers(Candidate), & &1.name)

    for trigger <- DemoScheduler.triggers() do
      assert trigger in generated,
             "DemoScheduler schedules #{inspect(trigger)}, which no longer exists. " <>
               "Generated triggers: #{inspect(generated)}"
    end
  end

  test "the auto-reject timeout is one of them" do
    assert :__timeout_trigger_review_auto_reject in DemoScheduler.triggers()
  end
end
