defmodule AshWorkflowTest.Repo.Migrations.AddActionTimeoutWorkflow1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:action_timeout_workflows, [:state, :next_check_at],
             name: "ash_workflow_action_timeout_workflows_state_next_check_at_index",
             concurrently: true
           )

    create index(:action_timeout_workflows, [:state, :state_entered_at],
             name: "ash_workflow_action_timeout_workflows_state_state_entered_at_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists(
      index(:action_timeout_workflows, [:state, :state_entered_at],
        name: "ash_workflow_action_timeout_workflows_state_state_entered_at_index"
      )
    )

    drop_if_exists(
      index(:action_timeout_workflows, [:state, :next_check_at],
        name: "ash_workflow_action_timeout_workflows_state_next_check_at_index"
      )
    )
  end
end
