defmodule AshWorkflowTest.Repo.Migrations.AddEveryLastFiredColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:every_until_workflows) do
      add(:waiting_reminder_last_fired_at, :utc_datetime_usec)
      remove(:repeat_started_at)
    end

    drop_if_exists(
      index(:every_until_workflows, [:state, :state_entered_at],
        name: "ash_workflow_every_until_workflows_state_state_entered_at_index"
      )
    )

    execute("""
    UPDATE every_until_workflows SET waiting_reminder_last_fired_at = state_entered_at;
    """)
  end

  def down do
    execute("""
    SELECT 1;
    """)

    create index(:every_until_workflows, [:state, :state_entered_at],
             name: "ash_workflow_every_until_workflows_state_state_entered_at_index",
             concurrently: true
           )

    alter table(:every_until_workflows) do
      add(:repeat_started_at, :utc_datetime_usec)
      remove(:waiting_reminder_last_fired_at)
    end
  end
end
