defmodule AshWorkflowTest.Repo.Migrations.AddScreeningWorkflow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:screening_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:candidate_name, :text, null: false)
      add(:should_fail, :boolean, null: false, default: false)
      add(:screen_score, :bigint)

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "screening")
    end
  end

  def down do
    drop(table(:screening_workflows))
  end
end
