defmodule AshWorkflowTest.Repo.Migrations.AddEveryUntilWorkflow1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:every_until_workflows, [:state, :state_entered_at],
             name: "ash_workflow_every_until_workflows_state_state_entered_at_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists(
      index(:every_until_workflows, [:state, :state_entered_at],
        name: "ash_workflow_every_until_workflows_state_state_entered_at_index"
      )
    )
  end
end
