defmodule AshWorkflowTest.Repo.Migrations.AddWallClockWorkflow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wall_clock_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:title, :text, null: false)
      add(:candidate_time_zone, :text, null: false)
      add(:digest_count, :bigint, null: false, default: 0)

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:waiting_digest_last_fired_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "waiting")
    end

    create index(:wall_clock_workflows, [:state, :waiting_digest_last_fired_at],
             name: "ash_workflow_wall_clock_workflows_state_waiting_digest_last_fired_at_index"
           )
  end

  def down do
    drop_if_exists(
      index(:wall_clock_workflows, [:state, :waiting_digest_last_fired_at],
        name: "ash_workflow_wall_clock_workflows_state_waiting_digest_last_fired_at_index"
      )
    )

    drop(table(:wall_clock_workflows))
  end
end
