defmodule AshWorkflowTest.Repo.Migrations.AddActionTimeoutWorkflow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:action_timeout_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:reminders, :bigint, null: false, default: 0)
      add(:pings, :bigint, null: false, default: 0)
      add(:checks, :bigint, null: false, default: 0)
      add(:next_check_at, :utc_datetime_usec)

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:waiting_reminder_fired_at, :utc_datetime_usec)
      add(:waiting_ping_fired_at, :utc_datetime_usec)
      add(:waiting_check_fired_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "waiting")
    end
  end

  def down do
    drop(table(:action_timeout_workflows))
  end
end
