defmodule AshWorkflowTest.Repo.Migrations.AddRelatedZoneWorkflow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:candidates, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:name, :text, null: false)
      add(:time_zone, :text, null: false)
    end

    create table(:related_zone_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:title, :text, null: false)
      add(:digest_count, :bigint, null: false, default: 0)

      add(
        :candidate_id,
        references(:candidates,
          column: :id,
          name: "related_zone_workflows_candidate_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:waiting_digest_last_fired_at, :utc_datetime_usec)
      add(:state, :text, null: false, default: "waiting")
    end

    create index(:related_zone_workflows, [:state, :waiting_digest_last_fired_at],
             name: "ash_workflow_related_zone_workflows_state_waiting_digest_last_fired_at_index"
           )
  end

  def down do
    drop_if_exists(
      index(:related_zone_workflows, [:state, :waiting_digest_last_fired_at],
        name: "ash_workflow_related_zone_workflows_state_waiting_digest_last_fired_at_index"
      )
    )

    drop(table(:related_zone_workflows))

    drop(table(:candidates))
  end
end
