defmodule AshWorkflowTest.Repo.Migrations.FireAtWorkflow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:fire_at_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:candidate_name, :text, null: false)
      add(:expires_at, :utc_datetime_usec)

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "pending")
    end
  end

  def down do
    drop(table(:fire_at_workflows))
  end
end
