defmodule AshWorkflowTest.Repo.Migrations.AddScreeningTransitionLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:screening_transitions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:from_state, :text)
      add(:to_state, :text, null: false)
      add(:transition_name, :text, null: false)
      add(:occurred_at, :utc_datetime_usec, null: false)
      add(:triggered_by, :text, null: false)

      add(
        :workflow_id,
        references(:screening_workflows,
          column: :id,
          name: "screening_transitions_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:screening_transitions, "screening_transitions_workflow_id_fkey"))

    drop(table(:screening_transitions))
  end
end
