defmodule AshWorkflowTest.Repo.Migrations.FireAtWorkflow1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @disable_ddl_transaction true
  @disable_migration_lock true

  def up do
    create index(:fire_at_workflows, [:state, :expires_at],
             name: "ash_workflow_fire_at_workflows_state_expires_at_index",
             concurrently: true
           )
  end

  def down do
    drop_if_exists(
      index(:fire_at_workflows, [:state, :expires_at],
        name: "ash_workflow_fire_at_workflows_state_expires_at_index"
      )
    )
  end
end
