defmodule AshWorkflowTest.Repo.Migrations.InitialWorkflowTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:approval_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:title, :text, null: false)
      add(:should_fail, :boolean, null: false, default: false)
      add(:processed_at, :utc_datetime_usec)

      add(:state_entered_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:state, :text, null: false, default: "processing")
    end
  end

  def down do
    drop(table(:approval_workflows))
  end
end
